version: '3.9'
services:
  api-edi-system:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        MAIN_PKG: .           
    image: api-edi-system:latest
    volumes: 
      - ./uploads/document/forecast:/uploads/document/forecast
      - ./uploads/document/invoice:/uploads/document/invoice
      - ./uploads/document/order:/uploads/document/order
      - ./uploads/images:/uploads/images
      - ./uploads/profile:/uploads/profile
    env_file:
      - .env    
    restart: always  
    depends_on:
      - redis 

    environment:
      - TOKEN_SECRET_KEY=${TOKEN_SECRET_KEY}
      - SERVER_PORT=${SERVER_PORT}

      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SET_FROM=${SMTP_SET_FROM}
      - SMTP_SET_FROM_NAME=${SMTP_SET_FROM_NAME}
      - SMTP_CUSTOM_CA_FILE=${SMTP_CUSTOM_CA_FILE}
      - SMTP_ALLOW_INVALID_TLS=${SMTP_ALLOW_INVALID_TLS}

      - LDAP_IP=${LDAP_IP}
      - LDAP_DNS=${LDAP_DNS}
      - LDAP_PASSWORD=${LDAP_PASSWORD}

      - REDIS_HOST=${REDIS_HOST}  
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

      - FRONTEND_BASE_URL=${FRONTEND_BASE_URL}

      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_DB=${SQL_DB}
      - SQL_HOST=${SQL_HOST}
      - SQL_PORT=${SQL_PORT}

      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1:1970/healthz || exit 1"]
      interval: 30s
      timeout:  3s
      retries:  3
    networks : 
      - edi-system-network

  redis:
    image:  redis:7-alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}  
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data 
    networks:
      - edi-system-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 3s
      retries: 5

  nginx-external-site:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - api-edi-system
    ports:
      - "1970:1970"
    restart: always
    networks:
      - edi-system-network

volumes:
  edi-system-volumn:
    driver:  local
  redis-data:  
    driver: local

networks:
  edi-system-network:
    driver: bridge